name: Add feature test

on:
  push:
    branches: [feat-add]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Steup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run add test
        run: node add-test.js
